### ISSUE TITLE
Alt key events are not handled properly by title-bar-replacer

### ISSUE THREAD

**Issue by skylize** [sindrets/atom-title-bar-replacer#12]
Test Setup: 
* Enable `title-bar-replacer`
* Open tree-view
* click in an editor pane.

Test: 
* Press key combination `Alt-\`.
* Expected: Focus moves to tree-view
* Actual: Focus moves to menu bar

With the package disabled, the menu bar only receives focus if you press `Alt` key twice or press a key combination for one of the menus (such as `Alt-F` for the `File` menu). The package is interfering with every possible `Alt` hotkey, including ones with `Ctrl` or `Shift` as well.

**Comment by sindrets** [comment]
@skylize this is true. The key interception was a little harsh in the previous version. One wrong assessment though: I specifically made sure not to intecept keystrokes with `Ctrl` and `Shift`. As long as those were pressed *before* the `Alt` key at least. 

Regardless: I just published 1.5.0, which has a much better way of dealing with keystroke interception. The application menu returns focus if a key is pressed that is unrelated to the menu context. Meaning that keystrokes with multiple modifiers (such as `Ctrl` and `Shift`) can now be pressed in any order. Other keystrokes with `Alt`, such as your mentioned `Alt-\` as well as i.e "Move to Next Diff": `Alt-g down` works too. I will however keep the behaviour to give the application menu focus on a single `Alt` press, as I prefer this behaviour to the original functionality. 

1.5.0 also fixes the bug with the title element you mentioned earlier.

**Comment by skylize** [comment]
Thank you. That's much better! 👍
