### ISSUE TITLE
Removing title-bar hangs

### ISSUE THREAD

**Issue by Severe1** [sindrets/atom-title-bar-replacer#14]
When i select the option to remove the windows title bar the modifying atom-window.js step appears to hang, with nog progress even after a couple of hours.

**Comment by sindrets** [comment]
@Severe1 It's a problem with Atom 1.21. I'm working on a patch. For more details, and a temporary workaround, see [this issue](https://github.com/sindrets/atom-title-bar-replacer/issues/10#issuecomment-329159546).
*Just remember to install asar **before** you run the bat.*

**Comment by sindrets** [comment]
@Severe1 v1.6 brings an implementation of the frame remover that is compatible with Atom v1.21.
