### ISSUE TITLE
Ship pre-patched app.asar using md5sum to verify version match

### ISSUE THREAD

**Issue by skylize** [sindrets/atom-title-bar-replacer#16]
The new implementation of patching app.asar is quite slow. I think you could improve the experience here by shipping a pre-patched copy from the most recent version of Atom. Run an md5 hash check to make sure you've got the right version, and if so do a simple and quick automatic backup/replace. If the hash check fails, then fall back to the manual patch.

**Comment by sindrets** [comment]
@skylize Sorry for taking so long to respond to this. I stopped working on this package for a while. 
Honestly , I don't think this is a very doable idea. `app.asar` is a ~200 mb file, something that would make for an unreasonably large node package. Further, I don't want to be forced to push a new update every time Atom updates. Besides, the amount of time spent downloading and installing a 200 mb update and copying the patched `app.asar` would probably take about the same amount of time that the current implementation uses. 

I recognize that the current implementation is very slow comapred to what it used to be prior to Atom deciding to return to Asar archiving, but I don't think this is a good solution, and I will therefore close this issue. Nevertheless, thank you for the suggestion :)
