### ISSUE TITLE
Menu Bar Hover + Alt Key to open

### ISSUE THREAD

**Issue by 1e4** [sindrets/atom-title-bar-replacer#2]
Hi there,

First off thanks for a great package, there are very few things I dislike about atom, and one of them was the title and menu bar.

I would love it if you could press alt and the menu bar would show up, alongside that if you click a top item on the menu bar such as File, Edit, if you have over an adjacent one you shouldn't need to click it again.

Would either of these be possible?

**Comment by sindrets** [comment]
Hello @1e4! Thank you for the feedback. I felt the exact same way as you for a long time, which led me to creating this  package for myself a while ago. It was only recently I found out that others had the same problem, which convinced me to publish the package. 

I appreciate your feature requests, and I plan on implementing them soon. I plan to make the menu bar alt-toggle, obey Atom's own setting for this feature. Menus opening on hover is a functionality I don't really like myself, hence why the feature is not present at the moment. However, I want this functionality to be available at least as an option. 

I am traveling at the moment, and will unfortunately not be able to work on the package for about a week. I will resume development when I return. Cheers!

**Comment by 1e4** [comment]
Hey @sindrets all sounds good, have fun travelling

**Comment by sindrets** [comment]
Menu bar auto hide, and adjacent category opening on mouse hover are now present as settings in v1.2.0 👍
