### ISSUE TITLE
minimize to systemtray

### ISSUE THREAD

**Issue by petKitsune** [sindrets/atom-title-bar-replacer#20]
is there a possibility to add a right click 
or option to the minimize button 
to sent Atom to the systemtray

**Comment by sindrets** [comment]
@petKitsune This is probably possible, but I'm questioning its usefulness. This is not a native function in neither Atom, nor Windows. I'll mark this as an enhancement, but I doubt I'll implement it, unless more people show interest for this.

**Comment by petKitsune** [comment]
it is indeed not a native function
but if you run programs portable, some like Atom takes a long time to load on older systems
for me it is more convenient to keep the program running in the systray, 1 click and its back up
I use RBTray for that, but it does not work on Atom after the patch
I needed this function more, so I reverse all

thanks anyway
still love the patch

**Comment by sindrets** [comment]
@petKitsune Okay, I did some experimenting for you. Put this in your `init.coffee`. It will let you minimize to tray by shift clicking the minimize button:
```coffeescript
###
    Minimize to tray
    @author github.com/sindrets
###

remote = require('electron').remote
rootPath = process.execPath.replace(/\\/g, '/')
rootPath = rootPath.substr(0, rootPath.lastIndexOf('/', rootPath.lastIndexOf('/') - 1) + 1)
shift = false
wasMaximized = false
workspace = document.querySelector('atom-workspace')
workspace.addEventListener 'keydown', (e) ->
    shift = e.shiftKey
    wasMaximized = atomWindow.isMaximized()
    return
workspace.addEventListener 'keyup', (e) ->
    shift = e.shiftKey
    return
atomWindow = atom.getCurrentWindow()
wasMaximized = atomWindow.isMaximized()
atomWindow.on 'minimize', (e) ->
    if shift
        e.preventDefault()
        atomWindow.hide()
    return
contextMenu = remote.Menu.buildFromTemplate([
    {
        label: 'Show'
        click: ->
            atomWindow.show()
            shift = false
            if wasMaximized
                atomWindow.maximize()
            return
    }
    {
        label: 'Hide'
        click: ->
            atomWindow.hide()
            return
    }
    {
        label: 'Quit'
        click: ->
            atom.close()
            return
    }
])
window.tray = new (remote.Tray)(rootPath + 'app.ico')
window.tray.setToolTip 'Atom'
window.tray.setContextMenu contextMenu

############################
```

**Comment by petKitsune** [comment]
many thanks for the effort

what i can see
atom disappears in the running applications and stays in the running processes
but it doesn't show the systray icon
AnVir also shows "No windows or system tray icon" after shift-LMB on the minimize

when I got the time tomorrow I will build a clean atom portable to check if the problem is somehow related to the modifications i got in this one

**Comment by sindrets** [comment]
@petKitsune I didn't pick up that you were using a portable version. If you read through the code, you will see that the Tray object requires the path to a `.ico` file for the tray entry icon. The portable version doesn't come with the icon. Just copy one over and adjust the `rootPath` variable. as well as the following line to lead to whatever name you have given the icon file:
```coffeescript
window.tray = new (remote.Tray)(rootPath + 'app.ico')
```

**Comment by petKitsune** [comment]
big thanks
works like a charm :D

looks like no one else need this function
so i can close this one

**Comment by petKitsune** [comment]
nice work
whit the menu it's even better than RBTray
I like it
thx
