### ISSUE TITLE
One pixel up-left offset when window maximized and active

### ISSUE THREAD

**Issue by Thooto** [sindrets/atom-title-bar-replacer#23]
Hi,
When atom is in maximized view with the title bar replaced, the whole content of the window appears to be offset by one pixel up and one pixel left, showing a one pixel wide black bar in the bottom and in the right of the window.

When atom is not active (by that I mean you are using another program) the offset disappears but comes back at the moment you go back to atom.

Great plugin anyway, I love it. I hope you could solve that issue. (it is not related to the latest update, it also did that before)

**Comment by Thooto** [comment]
Edit : it only happens on one of my computers ... So i think this issue is related to my graphics driver which already gave me other complications before ... I'll try it on other computers but I think the issue has to do with that particular computer otherwise I think you would have already hinted it. I'll let you know and if I can't reproduce the issue I'll close it.

**Comment by Thooto** [comment]
Managed to properly update graphic drivers that were blocked from updating by oem since the beginning. Discovered that thanks to you in a way :) . Problem gone. Issue closed!

**Comment by sindrets** [comment]
@Thooto glad you figured it out :)
