### ISSUE TITLE
"Windows frame remover" does not work here

### ISSUE THREAD

**Issue by patrickmast** [sindrets/atom-title-bar-replacer#28]
Hello,

I use latest Windows 10 Pro x64 with latest Atom (1.25.0 x64). I can not get the Windows frame removed from the Atom editor. I already tried the "Windows frame remover utility".

Thanks!

**Comment by sindrets** [comment]
@patrickmast I'm gonna need more information. In what sense does it not work? Does it crash? Does it output any errors in the console? Did you follow the instructions and replace `app.asar` with the generated `app-FRAMELESS.asar`? Did the frame remover run, and return the success message? 

I just ran the frame remover on my end on Atom 1.25, and it worked as expected.

**Comment by patrickmast** [comment]
Hello, I'm very sorry. Seems I forgot 1 step in the remover process. Works as expected now!! Thanks!
