### ISSUE TITLE
"Close Category on Re-click" option?

### ISSUE THREAD

**Issue by 3DanielK** [sindrets/atom-title-bar-replacer#30]
Currently, in the menu bar, if you have a category open and you re-click it, it won't close.
With pretty much any other menu bar out there, a category will close if you re-click it,
So maybe add an option to make it be the way most menu bars work, where if you re-click an open category it will close?

**Comment by reseto** [comment]
oh yes please, at least in Windows this is standard

**Comment by sindrets** [comment]
Fixed in v2.0.0.
