### ISSUE TITLE
Yosemite Windows controls theme bug when unticked 'Automatically Select Title Bar Colours' option

### ISSUE THREAD

**Issue by ghost** [sindrets/atom-title-bar-replacer#33]
Icons don't hide inside Yosemite controls. Here is a gif: https://i.imgur.com/ZJCXkeN.gif

**Comment by sindrets** [comment]
@gold604 I see. It's adopting your given "Text Colour", but it certainly shouldn't be doing that for the Yosemite theme. Thanks for bringing this to my attention.

**Comment by sindrets** [comment]
Fixed in v2.0.0.
