### ISSUE TITLE
How to uninstall the package

### ISSUE THREAD

**Issue by vadimhp** [sindrets/atom-title-bar-replacer#37]
How do you uninstall this plugin properly? I've lost the native main menu bar as well as the native title bar after uninstalling this package. How do you return them?

**Comment by sindrets** [comment]
@vadimhp reinstall the package again. Run the `window frame remover`. Click `restore`. Follow the instructions.

**Comment by vadimhp** [comment]
Oh okay, thanks. That was not apparent. I think you need a section in your README on uninstalling.
Cheers!
