### ISSUE TITLE
Visual bug on maximise - Windows

### ISSUE THREAD

**Issue by WBSemple** [sindrets/atom-title-bar-replacer#39]
When maximising, atom will alternate between displaying correctly and [displaying like this](https://i.imgur.com/PwareHK.png) with a white bar and a gap above the title bar.

**Comment by binaryfunt** [comment]
This is a bug in Electron [#12971](https://github.com/electron/electron/issues/12971)

**Comment by sindrets** [comment]
Closing this, as the bug is unrelated to this package.
