### ISSUE TITLE
About atom updates

### ISSUE THREAD

**Issue by dmase44** [sindrets/atom-title-bar-replacer#40]
If I add title-bar-replacer in the core options not to update the package, will an Atom version update still 
replace the app.asar file? 

Thanks for a great package, Dave

**Comment by sindrets** [comment]
@dmase44 sorry for not getting back to you on this. I don't really work on this package anymore.
To answer your question: yes, an atom update will always replace the `app.asar` file. The asar is an archive containing Atom's source files, thus it has to be replaced in order to update Atom.

**Comment by dmase44** [comment]
Thanks for your reply,

Shame you are not working on this package any more as it makes atom like it should be, love it.

After a couple atom version updates I found replacing the app.asar file a simple effort.

Anyway, I thank for a great package I will use it til atom won’t work with it any more at which time I’ll  stay with the version that still works.

Thanks for your time, Dmase
