### ISSUE TITLE
Default title bar doesn't disappear (Windows)

### ISSUE THREAD

**Issue by ReaperCrewGreen** [sindrets/atom-title-bar-replacer#41]
When I install this the default title bar does not go away instead now I have two title bars.
![capture](https://user-images.githubusercontent.com/24995216/45126121-931fab80-b126-11e8-962f-c236ebb77607.PNG)

**Comment by sindrets** [comment]
Please read the README and follow the instructions.

**Comment by alivefromsomewhere** [comment]
I followed the instructions. both from the settings and the menu, 'Window frame remover' doesn't work. retrying only causes atom to get stuck on "Deleting previously modified 'app-FRAMELESS.asar'.." with an error block handing in the back.
![image](https://user-images.githubusercontent.com/36825810/48957526-e8fb3700-ef50-11e8-949d-94667234fe35.png)
also, when attempting to keep the package menu with the native title bar and disabling the new one. it reappears on restart.
