### ISSUE TITLE
Wrong prosition of sub-menu when opened in full-screen

### ISSUE THREAD

**Issue by AlexGuo1998** [sindrets/atom-title-bar-replacer#46]
How to reproduce:
1. View - Toggle Full Screen
2. File - Exit
3. Re-launch Atom. It would open in full-screen mode
4. Open menu

![sub-menu-broken](https://user-images.githubusercontent.com/25975864/49494778-bc71e400-f89b-11e8-91f4-0f788c32575c.png)

I'm running on Windows 10 x64, Atom border removed.

**Comment by HintonR** [comment]
Hello, this is still an issue

**Comment by sindrets** [comment]
Fixed in v2.0.0.
