### ISSUE TITLE
Uncaught Exception : unable to find a valid app

### ISSUE THREAD

**Issue by misterguick** [sindrets/atom-title-bar-replacer#47]
Hi, 

I followed the steps and rename the .bak file to .asar etc ... But when I want to lauch atom after installation is complete, I get this : 
![image](https://user-images.githubusercontent.com/31132042/55153609-2a942c80-5153-11e9-83cf-8a7de57c946b.png)

But everything is fine after using the back-up of course, but the title bar is still there (accompanied by the custom one).

I'm on Windows 10, using I think the last atom version.

Thank you for you work mate !

**Comment by sindrets** [comment]
You're not supposed to rename the .bak file unless you want to restore Atom to default behaviour. The .bak file is a copy of the original `app.asar`. The patched app is called `app-FRAMELESS.asar`. ***This*** is the file you want to rename to complete the patch.
To be clear, your resources dir should contain these files after running the frame remover:
```
.
├── app.asar			(the original app. DELETE THIS)
├── app.asar.bak		(a backup of the original app)
└── app-FRAMELESS.asar		(the patched app. RENAME THIS)
```
After deleting `app.asar` and replacing it with `app-FRAMELESS.asar`, your dir should look like this:
```
.
├── app.asar			(app-FRAMELESS.asar renamed)
└── app.asar.bak		(a backup of the original app)
```
