### ISSUE TITLE
Title bar overlaps

### ISSUE THREAD

**Issue by finnmerlett** [sindrets/atom-title-bar-replacer#48]
Though this package works very well for the most part, when you decrease the window size too much the title, menu bar and min/max/close buttons overlap messily. A basic fix would be to cut off the title where it overlaps, a more thorough solution would be to contract the title when needed (with ... to show contraction), shorten the title to just 'Atom' when window was less than a certain width, and move later menubar items to a dropdown menu when the window is too small to allow 'Atom', the min/max/close buttons **and** all of the menu bar items.

**Comment by sindrets** [comment]
Fixed in v2.0.0. The title text is now hidden when it intersects with the menu bar.
