### ISSUE TITLE
Hide titlebar when fullscreen?

### ISSUE THREAD

**Issue by branden-akana** [sindrets/atom-title-bar-replacer#5]
While this package is great for when I have Atom windowed, most of the time I'm working while it's fullscreen. At the moment, I can still see the titlebar while it's fullscreen.

Could you perhaps have an option or even just the functionality for the titlebar to hide itself during fullscreen?

**Comment by sindrets** [comment]
@branden-akana This is a great idea. Didn't think about that. I'll add this behaviour in the next update.

**Comment by sindrets** [comment]
@branden-akana This feature is now present, and the default setting in v1.3.0 👍
