### ISSUE TITLE
Menu Bar Disappeared

### ISSUE THREAD

**Issue by dogactoklu** [sindrets/atom-title-bar-replacer#50]
Right-clicked on the Menu Bar and accidentally selected "Toggle Menu Bar". Now it's gone and ALT shortcuts do not work. Tried bringing up the settings to reset to defaults, CTRL+' also doesn't work. Restarting the application also proved useless.

**Comment by navneet7723** [comment]
same issue

**Comment by sindrets** [comment]
From the README:
> <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd> - Toggle menu bar visibility

All operations are also available from the command pallette:
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> > "Title Bar Replacer: Toggle Menu Bar"
