### ISSUE TITLE
'Remove window frame' does not work in 1.39.0-beta3 on Win x64

### ISSUE THREAD

**Issue by dima-y** [sindrets/atom-title-bar-replacer#53]
Subject says it all. The process completes 'successfully', I close Atom, rename the new file to app.azar, start Atom and the standard Windows menu is still there. Worked fine in 1.38-beta that I used previously.

**Comment by dima-y** [comment]
FWIW, works fine in 1.38.2 x64.

**Comment by vuther** [comment]
I have the same issue as well.

**Comment by Moustachey** [comment]
Same experience as @vuther , this doesn't work on the latest public release version of Atom.

**Comment by petKitsune** [comment]
same
Atom 1.39
win10x64

**Comment by kolikons** [comment]
i have the same issue
1.39.0 x64 win10x64

**Comment by Doskii** [comment]
Same as well. Just updated to 1.39.0 (win10 64bit) from 1.36.0 and it isn't removing the title bar anymore.

**Comment by sgmckay25** [comment]
Same 
atom 1.39.0 (win10 64bit) from app-1.38.2

**Comment by sindrets** [comment]
I was about to pronounce this plugin dead when I saw this issue, as I don't maintain this plugin anymore, but fortunately it was a very easy fix. 
Fixed in v1.8.3 🎉

**Comment by petKitsune** [comment]
thanks for creating this plugin
and spending your time to maintain it till now

its working again 
thanks for the fix

**Comment by Doskii** [comment]
Like @petKitsune said. Thanks for making and maintaining this plugin ❤️ I really don't understand why this isn't standard in Atom. The Windows title-bar is blinding with any dark theme 😛
