### ISSUE TITLE
Removing the native title bar on Windows crash

### ISSUE THREAD

**Issue by kudlav** [sindrets/atom-title-bar-replacer#54]
Uncaught Error: Unable to read header size
---
...\.atom\packages\title-bar-replacer\node_modules\asar\lib\disk.js:77

I am unable to reach error message, because this plugin cover screen with modal window and in %Appdata% I didn't find any logs.

Atom 1.39.1
Windows 10 1809 (32b)

**Comment by petKitsune** [comment]
works fine on
Atom 1.39.1 [+ new 1.40.0]
win10x64 1809 

i guess it got something to do with x32

**Comment by sindrets** [comment]
Fixed in v2.0.0.
