### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by silverkorn** [sindrets/atom-title-bar-replacer#6]
As suggested by @erroid, add a keyboard navigation for menu bar.

**Comment by silverkorn** [comment]
Including using:
- Left `Alt` to start/close the menu navigation;
- Arrows to navigate;
- 'Esc' to close the menu navigation;
- `Enter` to launch the selected item.

**Comment by sindrets** [comment]
@silverkorn Keyboard navigation is in the works, with all mentioned features :)

**Comment by sindrets** [comment]
@silverkorn, @erroid Full keyboard navigation has now been added to v1.3.0 👍

**Comment by silverkorn** [comment]
Little additional requests and it would be just like a real standard menu navigation: 
- Could you do that if there's nothing to unfold with the `Left`/`Right` arrows, the menu list change for the other top-most menu?
- Is it possible to highlight and navigated the top-most menus when using left `Alt` then pressing `Up`, `Down` or `Enter` to open the list?

![2017-08-25_16-09-15](https://user-images.githubusercontent.com/2325424/29730927-573711ba-89b0-11e7-845a-64d5c7c1b24c.gif)

Thanks!

**Comment by sindrets** [comment]
@silverkorn I added the requested features to version 1.3.1 :)
