### ISSUE TITLE
 Where is UI customization.

### ISSUE THREAD

**Issue by Wang-dami** [sindrets/atom-title-bar-replacer#60]
![Snipaste_2020-05-20_11-42-16](https://user-images.githubusercontent.com/48323554/82402516-26317e00-9a8f-11ea-93e6-7fcc2ab2c6d9.png)
![Snipaste_2020-05-20_11-43-25](https://user-images.githubusercontent.com/48323554/82402519-27fb4180-9a8f-11ea-90c6-c660d53a1629.png)

**Comment by sindrets** [comment]
@Wang-dami the UI customization options you can see in the picture are in the package settings. From the first picture it looks like something is overriding the css such that the correct icon font is not set for the controls. Or you have disabled font ligatures.

**Comment by Wang-dami** [comment]
I did't find the package settings .

![Snipaste_2020-05-20_20-11-57](https://user-images.githubusercontent.com/48323554/82444855-69630f80-9ad6-11ea-8fb9-07ab8cde3c4b.png)

**Comment by sindrets** [comment]
Yes, it should be there. Seems like the package is not installed correctly. Try reinstalling it through atom's package manager.
