### ISSUE TITLE
File menus open underneath left toolbar

### ISSUE THREAD

**Issue by ket-rivers** [sindrets/atom-title-bar-replacer#61]
Juno adds this side tool bar on the left. When i open the file menu, the menu opens beneath this toolbar. Is there somethin i can do to fix this?
Thanks.

![Untitled](https://user-images.githubusercontent.com/24192889/89383695-9900db80-d705-11ea-9e26-b0eaa99dae9b.png)

**Comment by sindrets** [comment]
Yes, you can adjust the css `z-index` of the title bar replacer, or decrease the `z-index` of Juno's side bar. I won't officially make that change though, because if I increase it any more it will overlap Atom's own modal windows which is undesirable. 
Put something like this in your stylesheet:
```less
.title-bar-replacer {
  z-index: 999999 !important;
}
```
