### ISSUE TITLE
Menu bar not toggling automatically

### ISSUE THREAD

**Issue by Tymotheus** [sindrets/atom-title-bar-replacer#68]
Hi, I have a following problem: after installing the package and configuring it, whenever I launch atom I need to every time manually toggle the menu bar (for example by alt-Shift-m) - it is by default hidden. Is there a way to have it toggled automatically, so I don't have to do it every time I launch Atom? Thanks.

**Comment by sindrets** [comment]
@Tymotheus there are 2 options for menu bar visibility:
* Display menu bar
  * Toggles the visibility on / off. 
  * <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd> is only a temporary change, and does not change this setting.
* Auto hide menu bar
  * Toggle the menu bar visibility by pressing the <kbd>alt</kbd> key.
  * If this is on, it overrides the "display menu bar" setting.

Did you have something else in mind?

**Comment by Tymotheus** [comment]
Yes, I mean I did not fully understand you so I will try to describe what I mean a little bit more precisely.
1. I am a Windows user. I wanted to get rid of the default Atom white title bar, so I installed your package.
2. I set up my Atom core settings: Core -> Title Bar -> hidden, so the default Atom title bar is not shown anymore.
3. I have now the title bar from atom-title-bar-replacer visible in my editor.

The problem is: when I launch Atom, it opens and there is a title bar from the package visible BUT there is no menu bar from the package visible. So when I want to see the menu bar - file, edit, view, selection etc. - so in fact pretty much every time I launch Atom, I need to type "Alt + Shift + M" to be able to view the menu bar. What I would like to have is to have it automatically visible when I launch Atom (so I do not need to type "Alt + Shift + M"). It is also weird for my because the title bar is automatically shown after starting Atom (no need to type "Ctrl + Alt + Shift + M"), but the menu bar - is not. 
So my question was: Is there a way to have the menu bar automatically shown after I launch Atom (just like the title bar is shown always, in my case) and if there is - how to do it?

**Comment by Tymotheus** [comment]
Ok I have just solved it. In the config file "config.cson" I had this part written:

"title-bar-replacer":
    general:
      displayMenuBar: false
      
 I just replaced it to true and the Menu Bar is now displaying correctly :)
 But thank you for the help!

**Comment by sindrets** [comment]
@Tymotheus  Yes, like I explained, that is one of the two settings that controls menu bar visibility. It is `true` by default though, so I'm a little confused as to how you managed to change it without knowing so. Like with any other package, you can find all the available settings by going to the package's settings page. Regardless, closing this issue.
