### ISSUE TITLE
Customizing title-bar font size

### ISSUE THREAD

**Issue by AdisonCavani** [sindrets/atom-title-bar-replacer#74]
Hi. Is it possible to customize title-bar font size, for example with Atom's style sheet?

**Comment by sindrets** [comment]
Yes. Just use the chromium dev tools to find the appropriate css selectors.

**Comment by AdisonCavani** [comment]
If anyone was wondering how to do this:
```
.title-bar-replacer .app-menu{
  font-size: 14px;
}
```
Thanks for help.

**Comment by sindrets** [comment]
@AdisonCavani If I remember correctly, `.tbr-style-compact` is only applied when you're using the compact style. So to make a more general selector that would work regardless of configuration I would change it to be simply:

```css
.title-bar-replacer .app-menu { /* rules... */ }
```
